// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNpJKEnAsJeQIUMC91wLBY803vVrPMIz4',
    appId: '1:212265099058:web:a3275d95efc7b9f8d3012b',
    messagingSenderId: '212265099058',
    projectId: 'tungleua',
    authDomain: 'tungleua.firebaseapp.com',
    storageBucket: 'tungleua.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkz2V-q4Dc3pDD4XHBd9aVnw4CpME7lJ0',
    appId: '1:212265099058:android:a454ca333264b320d3012b',
    messagingSenderId: '212265099058',
    projectId: 'tungleua',
    storageBucket: 'tungleua.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFLIPFGCS4lnFHvcNF2qW4QaDLAMLyE-8',
    appId: '1:212265099058:ios:d3cf4db970527891d3012b',
    messagingSenderId: '212265099058',
    projectId: 'tungleua',
    storageBucket: 'tungleua.appspot.com',
    iosClientId: '212265099058-ir6s7jcsk41is3ns88qejjmbfd0etjfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.tungleua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFLIPFGCS4lnFHvcNF2qW4QaDLAMLyE-8',
    appId: '1:212265099058:ios:96cd749b9c931eced3012b',
    messagingSenderId: '212265099058',
    projectId: 'tungleua',
    storageBucket: 'tungleua.appspot.com',
    iosClientId: '212265099058-m5m75lr22i6c6h2eirk7o35d91m03kpr.apps.googleusercontent.com',
    iosBundleId: 'com.example.tungleua.RunnerTests',
  );
}
