// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpCZr6ESGHjXhbF2ZWM6MW5MiyHFUBFmQ',
    appId: '1:399947108670:web:05610d383c644bc9361c6f',
    messagingSenderId: '399947108670',
    projectId: 'tungluea',
    authDomain: 'tungluea.firebaseapp.com',
    storageBucket: 'tungluea.appspot.com',
    measurementId: 'G-93TW5M3SGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhCFNCcSSCUZClKzf_NHWHLaBm2LTlP4g',
    appId: '1:399947108670:android:55a6dc419bf9bbe2361c6f',
    messagingSenderId: '399947108670',
    projectId: 'tungluea',
    storageBucket: 'tungluea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxX1r55jxD1mYBXT_Mi9MTeY-n3WQozkg',
    appId: '1:399947108670:ios:12eb9f600424499e361c6f',
    messagingSenderId: '399947108670',
    projectId: 'tungluea',
    storageBucket: 'tungluea.appspot.com',
    iosClientId: '399947108670-lj10ocm0vp9nch3ks7dqkr14td9hcgru.apps.googleusercontent.com',
    iosBundleId: 'com.example.tungleua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxX1r55jxD1mYBXT_Mi9MTeY-n3WQozkg',
    appId: '1:399947108670:ios:b17a293b6ea06c22361c6f',
    messagingSenderId: '399947108670',
    projectId: 'tungluea',
    storageBucket: 'tungluea.appspot.com',
    iosClientId: '399947108670-78f0q4n2g72qajqtetdshm5c39aoetkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.tungleua.RunnerTests',
  );
}
